/* Auto-generated by genmsg_java.py for file /data/private/luser/workspace/usc-ros-pkg/p2os/p2os_driver/msg/SonarArray.msg */

package org.ros.message.p2os_driver;

import java.nio.ByteBuffer;

public class SonarArray extends org.ros.message.Message {

  public org.ros.message.std_msgs.Header header = new org.ros.message.std_msgs.Header();
  public int ranges_count;
  public double[] ranges = new double[0];

  public SonarArray() {
  }

  public static java.lang.String __s_getDataType() { return "p2os_driver/SonarArray"; }
  @Override  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "2984921c09aef26ad253c7629937a5bb"; }
  @Override  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "Header header\n" +
"int32 ranges_count\n" +
"float64[] ranges\n" +
"\n" +
"================================================================================\n" +
"MSG: std_msgs/Header\n" +
"# Standard metadata for higher-level stamped data types.\n" +
"# This is generally used to communicate timestamped data \n" +
"# in a particular coordinate frame.\n" +
"# \n" +
"# sequence ID: consecutively increasing ID \n" +
"uint32 seq\n" +
"#Two-integer timestamp that is expressed as:\n" +
"# * stamp.secs: seconds (stamp_secs) since epoch\n" +
"# * stamp.nsecs: nanoseconds since stamp_secs\n" +
"# time-handling sugar is provided by the client library\n" +
"time stamp\n" +
"#Frame this data is associated with\n" +
"# 0: no frame\n" +
"# 1: global frame\n" +
"string frame_id\n" +
"\n" +
""; }
  @Override  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  @Override
  public SonarArray clone() {
    SonarArray c = new SonarArray();
    c.deserialize(serialize(0));
    return c;
  }

  @Override
  public void setTo(org.ros.message.Message m) {
    deserialize(m.serialize(0));
  }

  @Override
  public int serializationLength() {
    int __l = 0;
    __l += header.serializationLength();
    __l += 4; // ranges_count
    __l += 4 + ranges.length * 8; // ranges
    return __l;
  }

  @Override
  public void serialize(ByteBuffer bb, int seq) {
    header.serialize(bb, seq);
    bb.putInt(ranges_count);
    bb.putInt(ranges.length);
    for(double val : ranges) {
      bb.putDouble(val);
    }
  }

  @Override
  public void deserialize(ByteBuffer bb) {
    header.deserialize(bb);
    ranges_count = bb.getInt();

    int __ranges_len = bb.getInt();
    ranges = new double[__ranges_len];
    for(int __i=0; __i<__ranges_len; __i++) {
      ranges[__i] = bb.getDouble();
    }
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof SonarArray))
      return false;
    SonarArray other = (SonarArray) o;
    return
      header.equals(other.header) &&
      ranges_count == other.ranges_count &&
      java.util.Arrays.equals(ranges, other.ranges) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.header == null ? 0 : this.header.hashCode());
    result = prime * result + this.ranges_count;
    result = prime * result + java.util.Arrays.hashCode(this.ranges);
    return result;
  }
} // class SonarArray
