/* Auto-generated by genmsg_java.py for file /data/private/luser/workspace/usc-ros-pkg/p2os/p2os_driver/msg/MotorState.msg */

package org.ros.message.p2os_driver;

import java.nio.ByteBuffer;

public class MotorState extends org.ros.message.Message {

  public int state;

  public MotorState() {
  }

  public static java.lang.String __s_getDataType() { return "p2os_driver/MotorState"; }
  @Override  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "7a2f37ef2ba405f0c7a15cc72663d6f0"; }
  @Override  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "int32   state\n" +
"\n" +
""; }
  @Override  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  @Override
  public MotorState clone() {
    MotorState c = new MotorState();
    c.deserialize(serialize(0));
    return c;
  }

  @Override
  public void setTo(org.ros.message.Message m) {
    deserialize(m.serialize(0));
  }

  @Override
  public int serializationLength() {
    int __l = 0;
    __l += 4; // state
    return __l;
  }

  @Override
  public void serialize(ByteBuffer bb, int seq) {
    bb.putInt(state);
  }

  @Override
  public void deserialize(ByteBuffer bb) {
    state = bb.getInt();
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof MotorState))
      return false;
    MotorState other = (MotorState) o;
    return
      state == other.state &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + this.state;
    return result;
  }
} // class MotorState
