/* Auto-generated by genmsg_java.py for file /data/private/luser/workspace/usc-ros-pkg/p2os/p2os_driver/msg/DIO.msg */

package org.ros.message.p2os_driver;

import java.nio.ByteBuffer;

public class DIO extends org.ros.message.Message {

  public long count;
  public int bits;

  public DIO() {
  }

  public static java.lang.String __s_getDataType() { return "p2os_driver/DIO"; }
  @Override  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "d375575ab5b2233ab16927780da5f856"; }
  @Override  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "uint32 count\n" +
"uint16 bits\n" +
"\n" +
""; }
  @Override  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  @Override
  public DIO clone() {
    DIO c = new DIO();
    c.deserialize(serialize(0));
    return c;
  }

  @Override
  public void setTo(org.ros.message.Message m) {
    deserialize(m.serialize(0));
  }

  @Override
  public int serializationLength() {
    int __l = 0;
    __l += 4; // count
    __l += 2; // bits
    return __l;
  }

  @Override
  public void serialize(ByteBuffer bb, int seq) {
    bb.putInt((int)count);
    bb.putShort((short)bits);
  }

  @Override
  public void deserialize(ByteBuffer bb) {
    count = (long)(bb.getInt() & 0xffffffff);
    bits = (int)(bb.getShort() & 0xffff);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof DIO))
      return false;
    DIO other = (DIO) o;
    return
      count == other.count &&
      bits == other.bits &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (int)(this.count ^ (this.count >>> 32));
    result = prime * result + this.bits;
    return result;
  }
} // class DIO
